package com.difference.jpa_example;

import com.difference.spring_data_jpa_example.Employee;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;

public class Main {
    public static void main(String[] args) {
        EntityManagerFactory emf = JPAConfig.getEntityManagerFactory(); // now non-null
        EntityManager em = emf.createEntityManager();

        em.getTransaction().begin();
        Employee emp = new Employee();
        emp.setName("JPA Config"); // ID will be autogenerated if annotated
        em.persist(emp);
        em.getTransaction().commit();

        em.close();
        emf.close();
    }
}
